BEGIN;
CREATE TABLE IF NOT EXISTS users (
   id SERIAL PRIMARY KEY,
   name VARCHAR(100) NOT NULL,
   email VARCHAR(100) UNIQUE NOT NULL
);
ALTER TABLE users ADD COLUMN PASSWORD VARCHAR(64) NOT NULL DEFAULT "";

COMMIT;